-- Create analytics_visit table for tracking page visits
CREATE TABLE IF NOT EXISTS "public"."analytics_visit" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT REFERENCES "public"."user"("id") ON DELETE SET NULL,
    "ip" VARCHAR(45),
    "user_agent" TEXT,
    "path" VARCHAR(500) NOT NULL,
    "referrer" TEXT,
    "country" VARCHAR(100),
    "region" VARCHAR(100),
    "city" VARCHAR(100),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS "idx_analytics_visit_created_at" ON "public"."analytics_visit"("created_at");
CREATE INDEX IF NOT EXISTS "idx_analytics_visit_path" ON "public"."analytics_visit"("path");
CREATE INDEX IF NOT EXISTS "idx_analytics_visit_country" ON "public"."analytics_visit"("country");
