export interface BigFiveQuestion {
  id: number;
  text: string;
  dimension: "O" | "C" | "E" | "A" | "N";
  direction: "positive" | "negative";
  options: { text: string; score: number }[];
}

// The first 25 questions (ids 1-25) can be used for a short version (5 per dimension).
// The full 50 questions provide a comprehensive Big Five assessment.

export const bigFiveQuestions: BigFiveQuestion[] = [
  // O: Cởi mở (Openness) - 10 questions
  {
    id: 1,
    text: "Bạn thích khám phá các ý tưởng mới và sáng tạo.",
    dimension: "O",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 2,
    text: "Bạn thường cảm thấy khó chịu khi thử nghiệm những điều mới lạ.",
    dimension: "O",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 3,
    text: "Bạn yêu thích nghệ thuật, âm nhạc hoặc văn học.",
    dimension: "O",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 4,
    text: "Bạn thích làm việc theo cách truyền thống hơn là sáng tạo.",
    dimension: "O",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 5,
    text: "Bạn thường tưởng tượng và suy nghĩ về các ý tưởng trừu tượng.",
    dimension: "O",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 6,
    text: "Bạn thích trải nghiệm những nền văn hóa khác nhau.",
    dimension: "O",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 7,
    text: "Bạn không quan tâm nhiều đến các khái niệm lý thuyết.",
    dimension: "O",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 8,
    text: "Bạn thích tham gia các hoạt động sáng tạo như vẽ hoặc viết lách.",
    dimension: "O",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 9,
    text: "Bạn thường tò mò về nhiều lĩnh vực khác nhau.",
    dimension: "O",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 10,
    text: "Bạn thích các nhiệm vụ thực tế hơn là các ý tưởng trừu tượng.",
    dimension: "O",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },

  // C: Tận tâm (Conscientiousness) - 10 questions
  {
    id: 11,
    text: "Bạn luôn hoàn thành công việc đúng thời hạn.",
    dimension: "C",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 12,
    text: "Bạn thường trì hoãn các nhiệm vụ quan trọng.",
    dimension: "C",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 13,
    text: "Bạn thích lập kế hoạch chi tiết trước khi bắt đầu công việc.",
    dimension: "C",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 14,
    text: "Bạn thường làm việc một cách ngẫu hứng, không theo kế hoạch.",
    dimension: "C",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 15,
    text: "Bạn luôn kiểm tra kỹ lưỡng công việc để tránh sai sót.",
    dimension: "C",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 16,
    text: "Bạn giữ nơi làm việc của mình gọn gàng và ngăn nắp.",
    dimension: "C",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 17,
    text: "Bạn thường quên hoàn thành các nhiệm vụ được giao.",
    dimension: "C",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 18,
    text: "Bạn luôn nỗ lực để đạt được mục tiêu của mình.",
    dimension: "C",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 19,
    text: "Bạn thích làm việc có tổ chức và theo lịch trình.",
    dimension: "C",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 20,
    text: "Bạn thường bỏ qua các chi tiết nhỏ trong công việc.",
    dimension: "C",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },

  // E: Hướng ngoại (Extraversion) - 10 questions
  {
    id: 21,
    text: "Bạn cảm thấy tràn đầy năng lượng khi ở trong đám đông.",
    dimension: "E",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 22,
    text: "Bạn thích dành thời gian một mình hơn là giao tiếp xã hội.",
    dimension: "E",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 23,
    text: "Bạn dễ dàng bắt chuyện với người lạ.",
    dimension: "E",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 24,
    text: "Bạn cảm thấy mệt mỏi sau các sự kiện xã hội đông người.",
    dimension: "E",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 25,
    text: "Bạn thích là trung tâm của sự chú ý.",
    dimension: "E",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 26,
    text: "Bạn thường tìm kiếm cơ hội để giao lưu với người khác.",
    dimension: "E",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 27,
    text: "Bạn thích làm việc một mình hơn là làm việc nhóm.",
    dimension: "E",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 28,
    text: "Bạn cảm thấy thoải mái khi chia sẻ cảm xúc với người khác.",
    dimension: "E",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 29,
    text: "Bạn thường giữ suy nghĩ cho riêng mình.",
    dimension: "E",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 30,
    text: "Bạn thích tham gia các hoạt động nhóm sôi nổi.",
    dimension: "E",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },

  // A: Dễ chịu (Agreeableness) - 10 questions
  {
    id: 31,
    text: "Bạn thường đồng cảm với cảm xúc của người khác.",
    dimension: "A",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 32,
    text: "Bạn thường đặt lợi ích cá nhân lên trên lợi ích của người khác.",
    dimension: "A",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 33,
    text: "Bạn sẵn sàng giúp đỡ người khác mà không mong đợi đền đáp.",
    dimension: "A",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 34,
    text: "Bạn thường nghi ngờ ý định của người khác.",
    dimension: "A",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 35,
    text: "Bạn thích làm việc nhóm để đạt được mục tiêu chung.",
    dimension: "A",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 36,
    text: "Bạn thường ưu tiên duy trì sự hòa hợp trong các mối quan hệ.",
    dimension: "A",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 37,
    text: "Bạn hay chỉ trích người khác khi họ mắc lỗi.",
    dimension: "A",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 38,
    text: "Bạn dễ dàng tha thứ cho lỗi lầm của người khác.",
    dimension: "A",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 39,
    text: "Bạn thường tin tưởng vào lòng tốt của người khác.",
    dimension: "A",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 40,
    text: "Bạn thường cạnh tranh hơn là hợp tác với người khác.",
    dimension: "A",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },

  // N: Bất ổn cảm xúc (Neuroticism) - 10 questions
  {
    id: 41,
    text: "Bạn thường cảm thấy lo lắng hoặc căng thẳng trong các tình huống khó khăn.",
    dimension: "N",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 42,
    text: "Bạn thường giữ bình tĩnh ngay cả trong những tình huống áp lực cao.",
    dimension: "N",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 43,
    text: "Bạn dễ bị ảnh hưởng bởi những thay đổi bất ngờ.",
    dimension: "N",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 44,
    text: "Bạn hiếm khi cảm thấy buồn bã hoặc chán nản.",
    dimension: "N",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 45,
    text: "Bạn thường xuyên lo lắng về những điều có thể xảy ra sai sót.",
    dimension: "N",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 46,
    text: "Bạn dễ dàng vượt qua những thất bại trong cuộc sống.",
    dimension: "N",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 47,
    text: "Bạn thường cảm thấy khó chịu khi mọi thứ không theo ý muốn.",
    dimension: "N",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 48,
    text: "Bạn thường cảm thấy tự tin và ổn định về cảm xúc.",
    dimension: "N",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
  {
    id: 49,
    text: "Bạn dễ bị căng thẳng khi đối mặt với áp lực.",
    dimension: "N",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 50,
    text: "Bạn thường duy trì tâm trạng tích cực trong mọi tình huống.",
    dimension: "N",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: 2 },
      { text: "Không đồng ý", score: 1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: -1 },
      { text: "Rất đồng ý", score: -2 },
    ],
  },
];
