export interface MbtiQuestion {
  id: number;
  text: string;
  dimension: "E/I" | "S/N" | "T/F" | "J/P";
  direction: "positive" | "negative";
  options: { text: string; score: number }[];
}

// The first 30 questions (ids 1-30) can be used for the short version (7-8 per dimension).
// The full 60 questions provide a more comprehensive assessment.

export const mbtiQuestions: MbtiQuestion[] = [
  // E/I: Hướng ngoại (E) vs Hướng nội (I) - 15 questions
  {
    id: 1,
    text: "Bạn cảm thấy tràn đầy năng lượng khi tham gia các sự kiện xã hội với nhiều người.",
    dimension: "E/I",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 2,
    text: "Bạn thích dành thời gian một mình để suy nghĩ hoặc thư giãn.",
    dimension: "E/I",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 3,
    text: "Bạn thường dễ dàng bắt chuyện với người lạ.",
    dimension: "E/I",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 4,
    text: "Bạn cảm thấy mệt mỏi sau khi tham gia các buổi tụ họp đông người.",
    dimension: "E/I",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 5,
    text: "Bạn thích làm việc theo nhóm hơn là làm việc một mình.",
    dimension: "E/I",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 6,
    text: "Bạn thường suy nghĩ kỹ trước khi chia sẻ ý kiến của mình.",
    dimension: "E/I",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 7,
    text: "Bạn cảm thấy thoải mái khi là trung tâm của sự chú ý.",
    dimension: "E/I",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 8,
    text: "Bạn thích có không gian riêng để tập trung vào suy nghĩ của mình.",
    dimension: "E/I",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 9,
    text: "Bạn thường tìm kiếm cơ hội để gặp gỡ bạn bè mới.",
    dimension: "E/I",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 10,
    text: "Bạn thích đọc sách hoặc làm việc cá nhân hơn là tham gia tiệc tùng.",
    dimension: "E/I",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 11,
    text: "Bạn dễ dàng thể hiện cảm xúc với mọi người xung quanh.",
    dimension: "E/I",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 12,
    text: "Bạn cần thời gian riêng tư để nạp năng lượng sau ngày dài.",
    dimension: "E/I",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 13,
    text: "Bạn thích tham gia các hoạt động nhóm lớn.",
    dimension: "E/I",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 14,
    text: "Bạn thường giữ suy nghĩ cho riêng mình trước khi nói ra.",
    dimension: "E/I",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 15,
    text: "Bạn cảm thấy vui vẻ khi chia sẻ câu chuyện với đám đông.",
    dimension: "E/I",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },

  // S/N: Giác quan (S) vs Trực giác (N) - 15 questions
  {
    id: 16,
    text: "Bạn thường tập trung vào các chi tiết cụ thể hơn là bức tranh tổng thể.",
    dimension: "S/N",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 17,
    text: "Bạn thích suy nghĩ về các ý tưởng trừu tượng và khả năng trong tương lai.",
    dimension: "S/N",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 18,
    text: "Bạn tin tưởng vào những thông tin thực tế và có thể kiểm chứng.",
    dimension: "S/N",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 19,
    text: "Bạn thường tưởng tượng về những gì có thể xảy ra trong tương lai.",
    dimension: "S/N",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 20,
    text: "Bạn thích làm việc với các dữ kiện cụ thể hơn là lý thuyết.",
    dimension: "S/N",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 21,
    text: "Bạn bị thu hút bởi các ý tưởng sáng tạo và không truyền thống.",
    dimension: "S/N",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 22,
    text: "Bạn tập trung vào thực tại hơn là những gì có thể xảy ra.",
    dimension: "S/N",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 23,
    text: "Bạn thích khám phá các ý tưởng mới và trừu tượng.",
    dimension: "S/N",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 24,
    text: "Bạn ưu tiên kinh nghiệm thực tế hơn là lý thuyết trừu tượng.",
    dimension: "S/N",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 25,
    text: "Bạn thường nghĩ về ý nghĩa sâu xa của các sự kiện.",
    dimension: "S/N",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 26,
    text: "Bạn thích giải quyết vấn đề dựa trên sự kiện hiện tại.",
    dimension: "S/N",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 27,
    text: "Bạn bị hấp dẫn bởi các khái niệm và mô hình lý thuyết.",
    dimension: "S/N",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 28,
    text: "Bạn dựa vào giác quan để nhận thức thế giới xung quanh.",
    dimension: "S/N",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 29,
    text: "Bạn thường tìm kiếm các ý tưởng sáng tạo và mới mẻ.",
    dimension: "S/N",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 30,
    text: "Bạn thích các nhiệm vụ thực tế và cụ thể hơn là trừu tượng.",
    dimension: "S/N",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },

  // T/F: Lý trí (T) vs Cảm xúc (F) - 15 questions
  {
    id: 31,
    text: "Bạn đưa ra quyết định dựa trên logic và lý trí hơn là cảm xúc.",
    dimension: "T/F",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 32,
    text: "Bạn cân nhắc cảm xúc của người khác khi đưa ra quyết định.",
    dimension: "T/F",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 33,
    text: "Bạn ưu tiên sự công bằng hơn là cảm thông trong các tình huống tranh cãi.",
    dimension: "T/F",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 34,
    text: "Bạn dễ bị ảnh hưởng bởi cảm xúc của chính mình khi đưa ra quyết định.",
    dimension: "T/F",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 35,
    text: "Bạn thích phân tích vấn đề một cách khách quan và logic.",
    dimension: "T/F",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 36,
    text: "Bạn thường ưu tiên giá trị cá nhân hơn là logic khi ra quyết định.",
    dimension: "T/F",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 37,
    text: "Bạn xem trọng sự thật khách quan hơn là cảm xúc chủ quan.",
    dimension: "T/F",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 38,
    text: "Bạn cảm thấy quan trọng khi duy trì sự hòa hợp trong các mối quan hệ.",
    dimension: "T/F",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 39,
    text: "Bạn đánh giá tình huống dựa trên nguyên tắc logic.",
    dimension: "T/F",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 40,
    text: "Bạn thường đồng cảm với cảm xúc của người khác.",
    dimension: "T/F",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 41,
    text: "Bạn ưu tiên hiệu quả hơn là sự hài lòng của mọi người.",
    dimension: "T/F",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 42,
    text: "Bạn dễ tha thứ cho lỗi lầm của người khác vì cảm xúc.",
    dimension: "T/F",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 43,
    text: "Bạn phân tích ưu và nhược điểm một cách logic.",
    dimension: "T/F",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 44,
    text: "Bạn thường hành động dựa trên cảm giác cá nhân.",
    dimension: "T/F",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 45,
    text: "Bạn thích tranh luận dựa trên lập luận logic.",
    dimension: "T/F",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },

  // J/P: Nguyên tắc (J) vs Linh hoạt (P) - 15 questions
  {
    id: 46,
    text: "Bạn thích lên kế hoạch chi tiết trước khi bắt đầu một nhiệm vụ.",
    dimension: "J/P",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 47,
    text: "Bạn thích để mọi thứ linh hoạt và tự do thay vì lên kế hoạch trước.",
    dimension: "J/P",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 48,
    text: "Bạn thích hoàn thành công việc đúng hạn và có tổ chức.",
    dimension: "J/P",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 49,
    text: "Bạn cảm thấy thoải mái khi để các quyết định mở cho đến phút cuối.",
    dimension: "J/P",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 50,
    text: "Bạn thích làm việc theo lịch trình cố định và có cấu trúc.",
    dimension: "J/P",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 51,
    text: "Bạn thích thử nghiệm các cách tiếp cận mới thay vì tuân theo kế hoạch cố định.",
    dimension: "J/P",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 52,
    text: "Bạn cảm thấy dễ chịu khi mọi thứ được tổ chức và sắp xếp gọn gàng.",
    dimension: "J/P",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 53,
    text: "Bạn thích sự tự do trong việc thay đổi kế hoạch vào phút cuối.",
    dimension: "J/P",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 54,
    text: "Bạn thường hoàn thành nhiệm vụ trước thời hạn.",
    dimension: "J/P",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 55,
    text: "Bạn thích thích ứng với tình huống mới mà không cần kế hoạch.",
    dimension: "J/P",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 56,
    text: "Bạn ưu tiên sự ổn định và cấu trúc trong cuộc sống.",
    dimension: "J/P",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 57,
    text: "Bạn thường để mọi thứ mở cho các lựa chọn mới.",
    dimension: "J/P",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 58,
    text: "Bạn thích có danh sách việc cần làm hàng ngày.",
    dimension: "J/P",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 59,
    text: "Bạn thích khám phá mà không có lịch trình cố định.",
    dimension: "J/P",
    direction: "negative",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
  {
    id: 60,
    text: "Bạn cảm thấy hài lòng khi mọi thứ được lập kế hoạch rõ ràng.",
    dimension: "J/P",
    direction: "positive",
    options: [
      { text: "Rất không đồng ý", score: -2 },
      { text: "Không đồng ý", score: -1 },
      { text: "Trung lập", score: 0 },
      { text: "Đồng ý", score: 1 },
      { text: "Rất đồng ý", score: 2 },
    ],
  },
];
